runtime: custom

# use .1 values to force use of f1-micro instances
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

manual_scaling:
  instances: 1

network:
  forwarded_ports:
  - 8125

health_check:
  enable_health_check: True

